name: Update LED banner
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: talhacalik/led-scroll-action@v1
        with:
          text: HELLO WORLD !
          color: '#bff7ff'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'update led banner'
          file_pattern: led.svg
